<?php

require_once '../framework/functions.php';          // General functions
require_once '../framework/Config.php';             // Configuration

// Configurations
require_once '../config/conf.php';                  //

require_once '../lib/Haanga.php';                   //
require_once '../framework/Controller.php';         // Controlador base
require_once '../framework/Session.php';            // Gestión de sesion

require_once '../models/Model.php';                 //
require_once '../lib/spyc.php';
require_once '../lib/class.upload.php';

require_once '../lib/class.phpmailer.php';

?>
